SET SQL DIALECT 3;

CREATE DATABASE 'localhost:c:\temp\NMG_TEST.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1252;

CREATE TABLE CATEGORIES
(
  ID INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL
);

alter table CATEGORIES add constraint CATEGORIES_PK primary key (ID);

CREATE TABLE PRODUCTS
(
  ID INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  CATEGORY_ID INTEGER
);

alter table PRODUCTS add constraint PRODUCTS_PK primary key (ID);
alter table PRODUCTS add constraint PROD_CATEG_FK foreign key (CATEGORY_ID) references CATEGORIES(ID);

CREATE TABLE STORES
(
  ID INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1000)
);

alter table STORES add constraint STORES_PK primary key (ID);


CREATE TABLE INVENTORIES
(
  ID BIGINT NOT NULL,
  STORE_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY NUMERIC(16,3) NOT NULL,
  ADDED_AT DATE NOT NULL,
  MODIFIED_AT DATE
);

alter table INVENTORIES add constraint INVENTORIES_PK primary key (ID);
alter table INVENTORIES add constraint INVEN_STORE_FK foreign key (STORE_ID) references STORES(ID);
alter table INVENTORIES add constraint INVEN_PROD_FK foreign key (PRODUCT_ID) references PRODUCTS(ID);


CREATE GENERATOR GEN_CATEGORY_ID ;
CREATE GENERATOR GEN_INVENTORY_ID ;
CREATE GENERATOR GEN_PRODUCT_ID ;
CREATE GENERATOR GEN_STORE_ID ;

SET GENERATOR GEN_CATEGORY_ID TO 0;
SET GENERATOR GEN_INVENTORY_ID TO 0;
SET GENERATOR GEN_PRODUCT_ID TO 0;
SET GENERATOR GEN_STORE_ID TO 0;
